logging:
  config: classpath:log4j2-dev.xml
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 6969
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.102.155.74:3306/TPlanner?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password: root6868
#    timeout: 6000ms
#    lettuce:
#      pool:
#        max-active: 200
#        max-idle: 10
#        max-wait: -1
#        min-idle: 0

# 开启数据库字段映射驼峰模式
mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 10080
  tomcat:
      max-threads: 500
  ssl:
    key-store: classpath:4000650_sln.tplanner.cn.pfx
    key-store-password: g41V8S9G
    key-store-type: PKCS12
    ciphers: TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256

